apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: librechat
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/danny-avila/LibreChat.git
    path: helm/librechat
    targetRevision: main
    helm:
      valuesObject:
        image:
          registry: docker.io
          repository: librechat/librechat
          tag: chart-1.9.9
          pullPolicy: IfNotPresent
        global:
          librechat:
            existingSecretName: "librechat-credentials-env"
            existingSecretApiKey: OPENAI_API_KEY
          storageClass: nfs-client
          image:
            registry: docker.io
            repository: bitnami/mongodb
            tag: latest
        librechat:
          configYamlContent: |
            version: 1.0.8
            cache: true
            auth:
              type: oidc
              oidc:
                clientId: librechat
                clientSecret: ${OIDC_CLIENT_SECRET}
                issuer: https://sso.hnatekmar.xyz/realms/master
                autoRegister: true
                nameVar: preferred_username
            endpoints:
              openAI:
                apiKey: "${OPENAI_API_KEY}"
                modelDisplayLabel: "OpenAI"
              custom:
                - name: "Anthropic"
                  apiKey: "${ANTHROPIC_API_KEY}"
                  baseURL: "https://api.anthropic.com/v1"
                  models:
                    default: ["claude-3-haiku-20240307"]
                  titleConvo: true
                  titleModel: "claude-3-haiku-20240307"
                  modelDisplayLabel: "Anthropic"
          configEnv:
            ALLOW_REGISTRATION: "true"
            ALLOW_EMAIL_LOGIN: "true"
            MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
        mongodb:
          persistence:
            storageClass: nfs-client
            annotations:
              nfs.io/storage-path: "librechat-mongodb"
          image:
            tag: latest
        meilisearch:
          persistence:
            storageClass: nfs-client
            annotations:
              nfs.io/storage-path: "librechat-meilisearch"
        imageVolume:
          enabled: false
        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-cloudflare
          hosts:
            - host: librechat.hnatekmar.dev
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: librechat-tls
              hosts:
                - librechat.hnatekmar.dev
  destination:
    server: https://kubernetes.default.svc
    namespace: librechat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
