apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: librechat-librechat-images
  namespace: librechat
  annotations:
    nfs.io/storage-path: "librechat-uploads"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
