apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: librechat-credentials-env
    namespace: librechat
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:PtqvfUnVN8i8Hhr70nGmddXH9xD/2g/RYA==,iv:MGWHIQLd9EjmqzmNjIMaZ6W/C7cSJ2dHna9ouGp/aUk=,tag:Y7reyGgjaOd4fKFE5Xlf3Q==,type:str]
          type: ENC[AES256_GCM,data:YkbAPUHW,iv:f+/jZm9BYR4tdEWpyF59cClKjCSRn/fRshStA/aEsm8=,tag:nNo/KnPGhPrRVKHj0Oxh0A==,type:str]
          stringData:
            CREDS_KEY: ENC[AES256_GCM,data:n4hu8JiONkKISjHFWeTyAorIqpXIUhekQxXIrIKyDPX7B9Vplk3ViQ1G8U74Mc0ZJBHd2FP6UfHEElq085PN8A==,iv:EV9jgxWfIHBnvpMNRitLWUcUGdFjD8d6OETtizBFjQg=,tag:NBf6GfIzkolt5SKH4kLUNA==,type:str]
            CREDS_IV: ENC[AES256_GCM,data:L1Jtn9CjCh/IrSXhfoGj+Y057V0QZUC++fVsT3W6l0E=,iv:UJJgZ1v5eqG/DlC23UB5fL/qllUJMzCfgGyHdmNdyfA=,tag:FIqRQXZZs1YUhw3SrGM5fw==,type:str]
            JWT_SECRET: ENC[AES256_GCM,data:ZGDixUszxZv9gUdRlnNJhc3jEM27HB0KF3dTcfAXOIGs4r1cfCBKSvi4RGy+AMAO0CYobYgExr8ySE3PGrOiMA==,iv:kYtaQKxElNecluQ1ja84Cq5qLaW5+devposYLjDoHQU=,tag:AHTD8HQKD7hYZDawwX2WhQ==,type:str]
            JWT_REFRESH_SECRET: ENC[AES256_GCM,data:1zLzlMFwwmClEL+XQFAfoiCk7nJ4eOKopUwi3AkFDhQKZofjua+RtmiJAnNbKo/fQEuhBwQ7iaog4zGTvw/Tqg==,iv:jNjnR/hlCPg213jiz02kgQszZIcDGpJri2i5FIzD5LY=,tag:sXKhIiQRVXeLzoEFnlDSoA==,type:str]
            MEILI_MASTER_KEY: ENC[AES256_GCM,data:y4FHXhVU4s5jw2+lz72P49lcTwR5rd2ZIwLNH+A6DAmIqDATtQiAJvnl0ij/KOCYirimhgpM4ItS0qt6773Wzw==,iv:IhmG7ynw9xpZdvbEAsr51DLCh8QYfV11KaLG9bh1LCo=,tag:h+GyY3heguIfiQr4uY5sIw==,type:str]
            OPENAI_API_KEY: ENC[AES256_GCM,data:Dl32WqNh/mdyFqVU1Vn4G5QS27a8k8BtdT/OL5HGuRMGl/gcGhinCETkCZGXkzw8,iv:NvoSyHhcTvOBNGS8GH4TB0obHKDeYyFveXwfeNUDyEs=,tag:uaX1//UNhO+K7oiIK5FStw==,type:str]
            ANTHROPIC_API_KEY: ENC[AES256_GCM,data:+vdt+sXzq1sXmMlDhGxxQl3cU8eE2q9iWj7TJdTDgydeld8H+lrcbuVb8DRpmdei26s=,iv:mcp+gyTw12Z06D87fCeUZhjC5n5A2gAE1p9E6+1ilqY=,tag:ip3sH/xxWvRU9k0fLS2wnA==,type:str]
            OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:hYDhHZlUcYUzkCPC9B9vDGA4qLQy3au8jw0e6vYiMP4=,iv:P3+EnPWFcleCROPUB+8fVYTGcmHgzjyjkRmEdk4f42I=,tag:+MI+aCBOIHSnPBlt3FFU7A==,type:str]
sops:
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWEZQRGwyUlgrY29JRDJ0
            Z1NJbHhUQkFPUVQydmFUSWJscGlweXE4QkZ3CnNvZmRTM1QxcFpQVkpZT2hBN1hP
            Q3N0NHNvWTRsQlBUUnhsaHJlZ29OOXcKLS0tIGZoQVRyd0ZwbWR0ZW9SanNjM0U3
            cTlzdGtRSVArSTdORnQzRUlUN2IydUUKy5kxP0FKQ6+aPHGzuTOmpAG7udisXJ51
            vU7RC6sc/RJ+7nb0iOEB7BInEszejfZS+vYSum/PEqtuWPQXWLRfYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T22:56:55Z"
    mac: ENC[AES256_GCM,data:iE7hDwKzn+WN1T572G/FLb+Bge50yEGlL3ASMM6nwc93hZKoi2V2JKidrHNlbGlLtp9GLMZ01YVjH53k3ia5ahFhMsW7hdrsOTaeYzdRSej8SPqOe2epZcY4vLipRnpEotXCqZlHJoQktSErWTzRSz10SRUmgr2LJhMaLyoHMAM=,iv:x2guzNYw7qWQUEXPelfKSn7GJXJZC17W+JU6zgWAHa4=,tag:YnDOstqHNyl529k8oGr7Vw==,type:str]
    encrypted_suffix: Templates
    version: 3.12.1
