apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: thingsboard-db
    namespace: thingsboard
    annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
    # Templates suffix is what gets encrypted (see scripts/encrypt.sh)
    secretTemplates:
        - name: ENC[AES256_GCM,data:6hnWiOOedEE8nT4KLvg+cT4z1mg=,iv:AvtEZKhH+4tzAtoPOBn19bTklk6wqpOBFDHPDUucI3w=,tag:tHUupII3qqKrNQGdgcuQPw==,type:str]
          stringData:
            username: ENC[AES256_GCM,data:SJoM4ccGQGxpoOM=,iv:ivFWidOP4OsScOpJ5EdJHYCRNJOQ9Ze1EG6ykEDWlHk=,tag:K/oW5QkHSS3wglItw2h7LA==,type:str]
            password: ENC[AES256_GCM,data:PxtwAiHMuPzghEHcaO5ML+LJSzY05/3gYqqjM0yN6T4=,iv:szLXK+2YqaIx3TntwYrRILm5wRHXQ/Tm3lxLVx0SDz8=,tag:j2NDOWZkOZhj/fKU+p5KBQ==,type:str]
            url: ENC[AES256_GCM,data:SSv8ki4ItRpK0VXGnymZYGL90i9Sj87yflLHfFwHNcD/qlm/zKSC1S6oSjpqD3AkHWi6R+80z8HLdww2LnESwUCi0goPTjiR5u1fuDJ3eLi5xGc6Tg==,iv:wHMEhU6zEyXJG6HMJCiYv2kjKe21QkcGq8pzGFFFab8=,tag:jRh6EbMSsF9AO9z81fkCQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bVF2cnNpZ1Q4clhNcEZy
            UUI2N3ozNDVRSWZiNFRYWVA5MXNzaEJXZmdzCkpMbUJXbmp3OVdlVjl6ejJHN2s4
            WkI2bjlCTHZrRkhzMEw0VXlXakhKVE0KLS0tIEg4cHd3eDg4SEpZNlZDVjNPVThz
            dHhwYkcxVndGakhGd0RTQmxJUXIzWGMKZORFejaIGbIZprNpicYNLDkm0q9phTYF
            LBwoRebDSQGnD4q+Ly1IuMX5s1LEAuh1fyzCmNx+CgM7WbCxBv0sZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-12T09:04:51Z"
    mac: ENC[AES256_GCM,data:RS1QN5z3rGuRqXTUo5m/ubsfpA5f5iJ+swfjVarWapRHPt2FKM8VvrXMyzNKUhbQrMulEF0U6CDrx4m1RN2iKBPzq/OENZ/daPjn/b+SUIHHHo2eqx8VAxyVwSkpoe0CnLtPBuBIlUdt59wLjk7Z9ANXEnS+wNrF2soQgdGeqv4=,iv:Q0kFgzE+EfuMFp7BCLUrfR6DazJ15WeheV+eLPuMH/8=,tag:mwhITPF9Z+NMJRWNva2D6A==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.4
