apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:piRlJ59JNCXtZfcbvUGGYa+YfZKHV8Hdxlox,iv:2K0zNeXSk9+yv5zZ/Chjm26ELPew8CtTrRU8gjXTMd4=,tag:BK9hb/rPwVzAuYKYO5p4zA==,type:str]
          type: ENC[AES256_GCM,data:gtOF+WIp,iv:dA9l4uESUbh6TccMrmgpFbzJ6L8Nz40JolB1EUFX2pE=,tag:Kq8Ow1mQghPlArmq/D/yow==,type:str]
          stringData:
            api-token: ENC[AES256_GCM,data:V7Rg5Eh7mf5d3a4CQ2FyNZP3XEQfBt4OmIpC/EgugBGNYcDnR5ZJVA==,iv:9ZyL/bj7QtnrPaDy+GxT90HiOxh8Sy4ufQbQRUeCSlM=,tag:BsnAGnnCtNy38Ei1LuevVw==,type:str]
sops:
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTWVvQktMaElqdklrcjNL
            SVVFQmVjbjUvMjdselIrNisvM0pCSlBvelZzCkNNOW1QeWpYdEZPTkNOWDNXWWtN
            SkxHL2JKNEtzUGV1Tkl0dTRkTlNZU0UKLS0tIFcrR0VBZzVGOTFaZjR5Qm5HamIr
            T3lIdkxVOUY1UmhpcnZ1UVNjV3lhSlEKPvD+vFxswyirDJie69V5N4u9sSYU7p52
            pWuJyb+AZRjjbbS2GDeg2WToVr0hiXyuwOjMVbqshESOZ7K6m1EzKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-11T20:54:42Z"
    mac: ENC[AES256_GCM,data:QAEutgqnxYfJlZfU+IqdRM90rpZvOB7sjXecj5luwfcGVSRLR5uVZhn1YRktkvlNS8U30SofsSaV0L8EfC+RDkcRz4JJQN0wE09Iq5q+1fuK33YqOTEl51ux/ynxla9DdRXbtqXm6zOZu2Y6/UecNo7cc9rk7LQE8v40/m8z0Xc=,iv:Y+ke0hrMlI7ZVdSa1NOSdkC3nK+6z0msZ8MgBHSzKKI=,tag:0yMvRkZTR2i0AOopGR0usg==,type:str]
    encrypted_suffix: Templates
    version: 3.10.2
