apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: routeros-iac
    namespace: crossplane-system
    annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:er8X6U9uxfiHTSjo,iv:nurIO4NB/Y2zLho5InDWeu9i1FuKToCVYiKlN6AcDz0=,tag:fx8iykIfg8DrJpuRa+QV+w==,type:str]
          type: ENC[AES256_GCM,data:EjyODtgz,iv:GMY5kXRgzRt31S7Z5R6nGuYq9YcCP/AwRbxbzZUNExI=,tag:U3P1iE7YihLxEvZdRlLW1g==,type:str]
          stringData:
            username: ENC[AES256_GCM,data:s088,iv:IEjqvWqm10LRzHfIkI3Qkjr749wV+h1YCPiC4INDDDo=,tag:ucZoKnP+pe6K4ZSs3G2YtA==,type:str]
            password: ENC[AES256_GCM,data:TgkzPDqsFsDSR16SOehb3acSRXfPtWtTNmj6eHLrkw==,iv:unADFYpesTRVd4DK6rd5tfXUNBCMUfOI53MSJVJaayA=,tag:o5lkwGCOWLXM8VTUlD1PEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZnJuTWptRkE3a3RSeHRy
            cnRXUlhMbnRwRmxSbUNUQll2c20vVnFXaW1ZClFETWlDMi9zY2ZsZGNoeU1SVzNJ
            NThXQ1hkZEJhaXpPekkrWk1aQUJWWGcKLS0tIHY2NWhFZk1YZVVneGN5LzhJd3k4
            eGlhL2pQbEFBSW1IUlEzUm92RTJuZU0Kl5LxllZcp993sIvrKwmQlACH4Enh8QJh
            l9MaqKP77DEI8xndGQ6xCrNPfxu2d9MGFNpkbI12eSCRxGFL7SpTEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T11:54:16Z"
    mac: ENC[AES256_GCM,data:Zdt8CsVFohjS2zqG6K4v/A688Zp5ZXAWdm/1D/4eQss5H7BWrK/JGBemacUwJlHNM8+f8wzY00AN1fC27BlZFXHLN9Ur6LeZILglgNvNwhG8GfqVZmZ5Dz5Rd1Tx42+PbjsAlC0zN467DPT6OZztb9qph0CWmcxm5R6dVebe9qI=,iv:67zZnEtoVnd6X4xFPEZBOE9mvFNokE0StszxzOQUNJs=,tag:UyRkk7eUF3g5sTqynbuYng==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.9.4
