apiVersion: v1
kind: Namespace
metadata:
  name: nfs-provisioner
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-async
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
    - chart: nfs-subdir-external-provisioner
      repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
      targetRevision: 4.0.18
      helm:
        releaseName: nfs-subdir-external-provisioner
        valueFiles:
          - $repo/devops/argocd/nfs/values.yaml
    - repoURL: 'https://github.com/hnatekmarorg/devops-cluster.git'
      targetRevision: main
      ref: repo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nfs-provisioner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false