apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-async
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    chart: nfs-subdir-external-provisioner
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    targetRevision: 4.0.18
    helm:
      releaseName: nfs-subdir-external-provisioner
      valuesObject:
        volume-name: nfs-async
        nfs:
          server: 192.168.88.25
          mountOptions:
            - hard
            - intr
            - async
            - proto=tcp
            - noacl
            - nfsvers=4.2
            - noatime
          path: /mnt/data/k8s
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nfs-provisioner
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:
      - CreateNamespace=true