"apiVersion": "v1"
"clusters":
- "cluster":
    "certificate-authority-data": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpVENDQVMrZ0F3SUJBZ0lRVWorRXRERDZCMUV5R29uRlJLV0xKREFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTJNRGt5TURBMU16UXhORm9YRFRNMk1Ea3hOekExTXpReApORm93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCT2w0Ly8zZjV3OTR3WUJBalV3VkxWWTUxdXVKNWYyNEVzV054dU1TZzNIYW1lR2dQQ2djaC9BME9pRTEKWEpJSytQaGxPTHRkUHBuNW96SGVGUGxGUTdtallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVVrQWFBSnJZdmp0RXJDbjNRZWFybW96L29SZG93Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU9JZzY1a0wKc1RBWGo5dmdNQURIL2ZGcFNPem9hc3k5UEhndUVpQ2tUai9VQWlBdEQySEV0NUw5NHNwY1AxZ1lMVmVLZjhCVQpRdXdvYXFXdFoxNDh2MjV5cGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    "server": "https://prod-k8s.srv.hnatekmar.dev:6443"
  "name": "prod"
"contexts":
- "context":
    "cluster": "prod"
    "user": "sso:kubectl-hnatekmar-xyz"
  "name": "prod"
"current-context": "prod"
"kind": "Config"
"users":
- "name": "sso:kubectl-hnatekmar-xyz"
  "user":
    "exec":
      "apiVersion": "client.authentication.k8s.io/v1"
      "args":
      - "get-token"
      - "--oidc-issuer-url=https://sso.hnatekmar.xyz/realms/master"
      - "--oidc-client-id=kubectl-hnatekmar-xyz"
      - "--oidc-extra-scope=email"
      "command": "kubelogin"
      "interactiveMode": "IfAvailable"
      "provideClusterInfo": false
