defaultSettings:
  kubernetesClusterAutoscalerEnabled: true
preUpgradeChecker:
  jobEnabled: false
longhornManager:
  tolerations:
  - key: "node/type"
    operator: "Equal"
    value: "storage"
    effect: "NoSchedule"
longhornDriver:
  tolerations:
  - key: "node/type"
    operator: "Equal"
    value: "storage"
    effect: "NoSchedule"