defaultSettings:
  kubernetesClusterAutoscalerEnabled: true
preUpgradeChecker:
  jobEnabled: false
longhornManager:
  tolerations:
  - key: "node/type"
    operator: "Equal"
    value: "storage"
    effect: "NoSchedule"
longhornDriver:
  storageNetwork: 192.186.88.1/24

  tolerations:
  - key: "node/type"
    operator: "Equal"
    value: "storage"
    effect: "NoSchedule"