
apiVersion: v1
stringData:
{{- if .Values.minio.access_key }}
  AWS_ACCESS_KEY_ID: {{ .Values.minio.access_key | quote }}
{{- else }}
  {{ fail "Please specify access key" }}
{{- end}}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.secret_key | quote }}
kind: Secret
metadata:
  name:  {{ printf "%s-minio-secret" .Values.prefix }}
  namespace: crossplane-system
---
apiVersion: minio.crossplane.io/v1
kind: ProviderConfig
metadata:
  namespace: crossplane-system
  name: {{print "%s-minio" .Values.prefix }}
spec:
  minioUrl: {{ .Values.minio.address | quote }}
  credentials:
    apiSecretRef:
      name:  {{ printf "%s-minio" .Values.prefix }}
      namespace: crossplane-system