apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sops
  namespace: argocd
spec:
  project: default
  sources:
    - chart: sops-secrets-operator
      repoURL: https://isindir.github.io/sops-secrets-operator/
      targetRevision: 0.22.0
      helm:
        releaseName: sops-secrets-operator
        valueFiles:
          - $repo/devops/argocd/sops/values.yaml
    - repoURL: 'https://github.com/hnatekmarorg/devops-cluster.git'
      targetRevision: main
      ref: repo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: sops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true