#!/bin/bash

export SIDERO_CONTROLLER_MANAGER_HOST_NETWORK=false
export SIDERO_CONTROLLER_MANAGER_DEPLOYMENT_STRATEGY=Recreate
export SIDERO_CONTROLLER_MANAGER_API_ENDPOINT=172.16.100.5
export SIDERO_CONTROLLER_MANAGER_SIDEROLINK_ENDPOINT=172.16.100.5

clusterctl init -b talos -c talos -i sidero