# The reader exception — one device, internet denied, LAN allowed.
#
# WHY THIS FILE EXISTS
# ----------------
# The matrix gives iot one row: "internet ✓ only, internal reach is the VPN's job". That is the right
# default for the WiFi segment and it is enforced (stage 3, phase 2). It is the wrong shape for exactly
# one device: a tablet used as an e-reader and to browse **internal** web services, where the point is
# to keep the vendor's telemetry inside the house rather than to give it internet access with nothing to
# reach.
#
# So this device gets the inverse of the iot row. Both halves are required — a WAN deny alone would
# leave it able to reach *nothing*, because the class drops below already refuse it every internal
# network:
#
#   * `reader_no_wan`      forward, src=reader-nets, out=WAN      → the device keeps no internet
#   * `reader_web_allow`   forward, src=reader-nets, dst=<class>  → …but may browse internal web ports
#   * `reader_router_dns`  input,   src=reader-nets, port 53      → name resolution without the internet
#   * `reader_router_ntp`  input,   src=reader-nets, udp 123      → clock without the internet
#
# DNS IS NOT OPTIONAL, AND THE FIREWALL ALONE DOES NOT DELIVER IT
# ----------------
# The iot DHCP scope hands out `dns-server=8.8.8.8` (read off the device, not inferred). Deny the
# internet and every host in the class keeps a resolver it can no longer reach. Accepting DNS at the
# router is only half the fix: the device has to be *told* to use it, or it will keep asking 8.8.8.8 and
# simply time out. Hence the per-lease option set below — one device, one DHCP option, no change to the
# class's own policy (which is deliberate: "iot keeps public DNS" stays true for the segment).
#
# The DNS accept carries **no protocol field on purpose**: a filtered resolver falls back to TCP when an
# answer is truncated, so a udp-only accept fails on exactly the large answers. Port 53 either way.
#
# NTP: THE ACCEPT IS FORWARD-LOOKING, AND THE CLOCK IS A REAL GAP
# ----------------
# The iot scope sets `ntp-none=true` (its own policy, matching iot's "public time" reasoning), so no
# client is told to ask anyone for time — this rule therefore permits traffic that is not currently
# invited. It is here so that advertising the router as the segment's time source (option 42) becomes a
# DHCP-side change rather than a firewall change as well. Until that happens the reader has no time
# source at all once its internet is gone, and a drifted clock breaks TLS against internal services:
# worth deciding deliberately rather than discovering. Measured 2026-09-19: `ntp.tf` declares the NTP
# server `enabled = true` while the device reports `enabled=false` — that drift is the blocker, and it
# belongs to the NTP work, not here.
#
# ORDERING (measured on the device 2026-09-19 — not assumed)
# ----------------
# Forward chain, as it actually is: the five `dst-address-list=wan` accepts sit at 2–6 but they match
# `connection-nat-state=dstnat`, i.e. inbound-published traffic, not egress — so they are irrelevant to
# this rule. A hand-made `drop` matching one MAC sits at 12 ("Disable internet for devices", 0 packets:
# the shape this file replaces with something reviewable). fasttrack and
# `accept established,related,untracked` sit at 17–18; the class drops at 21–33. There is no terminal
# `accept`, so unmatched traffic falls through and is accepted — which is precisely how iot keeps its
# internet today, and precisely what an appended drop pre-empts.
#
# Therefore:
#   * `reader_no_wan` is APPENDED (no `place_before`), the same convention as every other matrix drop.
#     It is matched before the fall-through, so new connections die immediately. Connections already
#     established when the rule lands, and anything fasttracked, can survive until they close: expected,
#     and measurable — the rule's byte counter stops climbing when the last of them expires.
#   * the ALLOWS carry explicit `place_before` anchors on the class drop they contradict, because an
#     appended accept would sit *below* those drops and never match. Same pattern as `iot_router_dhcp`.
#     Anchoring a brand-new rule costs nothing; anchoring a live rule would force its replacement.
#
# FAIL-OPEN, STATED PLAINLY
# ----------------
# The identity here is an address (`reader-nets`, one /32) claimed by a DHCP reservation, and the
# reservation is keyed on a MAC that this tablet **randomizes** (`46:FC:89:6A:6C:9C` is locally
# administered, i.e. generated by Android, not burned in). If the private MAC is ever reset, or the
# network is forgotten and re-joined, the lease changes, `reader-nets` matches nothing, and the device
# silently gets the iot row back: internet, no LAN. That failure is quiet by construction.
#   * Mitigation (do this on the device): Wi-Fi → the network → Privacy → "Use device MAC". Then the
#     reservation is on stable hardware and this stops being a caveat.
#   * Until then, verification is the counters on `reader_no_wan`: zero packets on a device that is in
#     use means the device is no longer matching.
#
# END STATE: if a second reader device appears, this file is the wrong answer — the honest move is a
# `reader` class (its own VLAN + SSID + DHCP scope + a matrix row), and this file is deleted with it.

locals {
  # The reader's identity, stated once: `main.tf` takes the address for `reader-nets` from here, and the
  # reservation in `dhcp.tf` claims the same address. A second literal is how a name and a rule drift.
  reader = {
    address = "172.16.70.123"
    mac     = "46:FC:89:6A:6C:9C"
    # The router on the iot segment — the estate's own resolver (`dns.tf`), which is what makes internal
    # names resolvable at all. Handing out 8.8.8.8 (the class default) to an internet-less device would
    # be an address that resolves nothing.
    resolver = "172.16.70.1"
  }

  # Destinations the reader may browse, each paired with the class drop it has to be placed above.
  # Web ports only: a reader has no business initiating anything else into the estate.
  reader_web = {
    SRV    = "srv-nets" # the reverse proxies and the services behind them
    COMPAT = "lan-nets" # the edge host and argocd still live in the flat segment (it is draining)
    VIP    = "svc-vips" # where internal ingress is heading — kept so this does not need editing later
  }
}

resource "routeros_ip_firewall_filter" "reader_no_wan" {
  chain              = "forward"
  action             = "drop"
  log                = true
  src_address_list   = "reader-nets"
  out_interface_list = "WAN"
  log_prefix         = "MTX-READER>WAN "
  comment            = "reader: internet denied by design (e-reader + internal browsing) — docs/firewall-matrix.md"
}

# Placed above each class drop it contradicts. Without these the reader reaches nothing: the iot row
# denies every internal network, and these are the narrow exceptions that make the device useful again.
resource "routeros_ip_firewall_filter" "reader_web_allow" {
  for_each = local.reader_web

  chain            = "forward"
  place_before     = routeros_ip_firewall_filter.iot_deny[each.key].id
  action           = "accept"
  src_address_list = "reader-nets"
  dst_address_list = each.value
  protocol         = "tcp"
  dst_port         = "80,443"
  comment          = "reader exception: internal web only (${each.key}) — firewall-matrix.md"
}

# The router itself. Above `iot_router_deny`, the same anchor `iot_router_dhcp` uses, and for the same
# reason: a catch-all deny is only as good as the accepts that sit above it.
# No `protocol`: DNS truncates to TCP, so udp-only would fail on the large answers.
resource "routeros_ip_firewall_filter" "reader_router_dns" {
  chain            = "input"
  place_before     = routeros_ip_firewall_filter.iot_router_deny.id
  action           = "accept"
  src_address_list = "reader-nets"
  dst_port         = "53"
  comment          = "reader exception: DNS (udp+TCP), because its internet is denied — firewall-matrix.md"
}

resource "routeros_ip_firewall_filter" "reader_router_ntp" {
  chain            = "input"
  place_before     = routeros_ip_firewall_filter.iot_router_deny.id
  action           = "accept"
  protocol         = "udp"
  src_address_list = "reader-nets"
  dst_port         = "123"
  comment          = "reader exception: the router as time source, once option 42 advertises it — firewall-matrix.md"
}

# The piece that makes the DNS accept mean something: hand this one lease a resolver it can reach.
# DHCP option 6 (DNS servers), attached to the reader's reservation in `dhcp.tf` via `option_set`.
# Per-lease, so the class keeps its own "public DNS" policy untouched.
resource "routeros_ip_dhcp_server_option" "reader_dns" {
  name    = "reader-dns"
  code    = 6
  value   = local.reader.resolver
  comment = "${local.managed_by} — the reader's resolver, reachable without internet"
}

resource "routeros_ip_dhcp_server_option_set" "reader" {
  name = "reader"
  # RouterOS takes this as a comma-separated string of option names, not a list (validate caught the
  # tuple form). Referencing the resource keeps the dependency edge.
  options = routeros_ip_dhcp_server_option.reader_dns.name
  comment = "${local.managed_by} — one device, one option set (reader)"
}
