{{- range .Values.models -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{.name}}
spec:
  cooldownPeriod: 120
  maxReplicaCount: {{.replicas | default 1}}
  pollingInterval: 15
  scaleTargetRef:
    name: {{.name}}
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://kube-prometheus-stack-prometheus.prometheus.svc.cluster.local:9090
      threshold: '1'
      query: {{ printf "sum(rate(nginx_ingress_controller_requests{host=\"%s\", path=\"/%s(/|$)(.*)\"}[1m]))" $.Values.llm.host .name }}
---
{{- end -}}