apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    cert-manager.io/cluster-issuer: {{ .Values.thingsboard.clusterIssuer }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.thingsboard.host }}
      secretName: {{ .Values.thingsboard.ingressTlsSecretName }}
  rules:
    - host: {{ .Values.thingsboard.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 8080
