---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bao-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - chart: openbao
      repoURL: https://openbao.github.io/openbao-helm
      targetRevision: 0.29.4
      helm:
        releaseName: openbao
        valueFiles:
          - $repo/devops/argocd/bao-staging/values.yaml
    - repoURL: 'https://github.com/hnatekmarorg/devops-cluster.git'
      targetRevision: main
      ref: repo
  destination:
    server: https://kubernetes.default.svc
    namespace: bao-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
