apiVersion: batch/v1
kind: Job
metadata:
  name: create-keycloak-provider-secret
  namespace: keycloak
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: secret-writer
      restartPolicy: Never
      containers:
        - name: create-secret
          image: bitnami/kubectl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Reading password from keycloak/keycloak..."
              PASSWORD=$(kubectl get secret keycloak -n keycloak -o jsonpath="{.data.admin-password}" | base64 -d)
              echo "Creating secret in crossplane-system..."
              TMP_FILE=$(mktemp)
              cat <<EOF > $TMP_FILE
              apiVersion: v1
              kind: Secret
              metadata:
                name: keycloak-master-realm
                namespace: crossplane-system
              type: Opaque
              stringData: 
                credentials: |
                  {
                    "client_id": "admin-cli",
                    "username": "user",
                    "password": "$PASSWORD",
                    "url": "https://keycloak.infra.hnatekmar.dev"
                  }
              EOF
              cat $TMP_FILE
              kubectl apply -f $TMP_FILE
