apiVersion: batch/v1
kind: Job
metadata:
  name: create-keycloak-provider-secret
  namespace: keycloak
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: secret-writer
      restartPolicy: Never
      containers:
        - name: create-secret
          image: bitnami/kubectl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Reading password from keycloak/keycloak..."
              PASSWORD=$(kubectl get secret keycloak -n keycloak -o jsonpath="{.data.admin-password}" | base64 -d)
              echo "Creating secret in crossplane-system..."

              kubectl apply -f - <<EOF
              apiVersion: v1
              kind: Secret
              metadata:
                name: keycloak-provider-creds
                namespace: crossplane-system
              type: Opaque
              stringData:
                creds.json: |
                  {
                    "user": "user",
                    "password": "$PASSWORD",
                    "host": "https://keycloak.infra.hnatekmar.dev"
                  }
                EOF