apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: grafana
  namespace: crossplane-system
spec:
  providerConfigRef:
    name: master-realm
  forProvider:
    clientId: grafana
    realmId: master
    standardFlowEnabled: true
    accessType: CONFIDENTIAL
    validRedirectUris:
      - https://grafana.hnatekmar.dev/login/generic_oauth
  writeConnectionSecretToRef:
    name: grafana-oidc
    namespace: prometheus