apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-writer
  namespace: keycloak
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-writer
  namespace: keycloak
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: crossplane-secret-writer
  namespace: crossplane-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "patch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-binding
  namespace: keycloak
subjects:
  - kind: ServiceAccount
    name: secret-writer
    namespace: keycloak
roleRef:
  kind: Role
  name: secret-writer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crossplane-secret-writer-binding
  namespace: crossplane-system
subjects:
  - kind: ServiceAccount
    name: secret-writer
    namespace: keycloak
roleRef:
  kind: Role
  name: crossplane-secret-writer
  apiGroup: rbac.authorization.k8s.io
