apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
  source:
    chart: keycloak
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 23.0.0  # Replace with the desired version
    helm:
      valuesObject:
        extraEnvVars:
          - name: JAVA_OPTS_KC_HEAP
            value: "-XX:MaxRAMPercentage=70 -XX:MinRAMPercentage=70 -XX:InitialRAMPercentage=50 -XX:MaxRAM=1G"
          - name: JAVA_OPTS_APPEND
            value: "-Dcom.redhat.fips=false"
        metrics:
          enabled: true
        persistence:
          enabled: true
          storageClass: "longhorn"  # Replace with your Ceph Block storage class name
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-cloudflare
          ingressClassName: nginx
          tls: true
          hostname: keycloak.infra.hnatekmar.dev
  destination:
    server: "https://kubernetes.default.svc"
    namespace: keycloak  # Replace with your desired namespace
