apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: proxmox-conf
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "ens19",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.88.0/24",
        "rangeStart": "192.168.88.1",
        "rangeEnd": "192.168.88.254",
        "routes": [
          { "dst": "192.168.88.0/24" }
        ],
        "gateway": "192.168.1.1"
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: atuin-conf
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "enp129s0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.88.0/24",
        "rangeStart": "192.168.88.1",
        "rangeEnd": "192.168.88.254",
        "routes": [
          { "dst": "192.168.88.0/24" }
        ],
        "gateway": "192.168.1.1"
      }
    }'
