apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: librechat-credentials
    namespace: librechat
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:fyTk49BdtnPos9Pj5CUvZxmHMy2q,iv:06e3NIbuPVPX9gMnpzpEuA+b0iSyXENQaS7I95S1AIY=,tag:vYiOqpXPVoyG7w5EUXz4zg==,type:str]
          type: ENC[AES256_GCM,data:c2a8H9xe,iv:bxEdRcGfXwJn8OCmnbXlkbrDFSLRUCsroX9/wM6Updg=,tag:/ITqxaE2zcwM1GqUFbrUvw==,type:str]
          stringData:
            CREDS_KEY: ENC[AES256_GCM,data:tL1g9j1hinx0ou8J7ulJTMFhEXj2ipuxE8NMvSUcEQxEldgqPcVD8Y1YXI3WKQKe,iv:H/zzD4a1Bix2h9tzoeNKLHpAyGPXiYZ7isKkMEDBjtI=,tag:wq6RvGh4HrAzOLmMr8gXBQ==,type:str]
            CREDS_IV: ENC[AES256_GCM,data:D5LtBGLtDzbvtYwlDygWWq3aIT43BN2RvS5eDJVWEKoVeRi42qmUa4AcUF3Oflo=,iv:FcBGZeG5uAW8zf0EK1w6l7G7etXdHQPcCEqTjlJcTtw=,tag:G1clpEXgm6UzTxQaV2MBjw==,type:str]
            JWT_SECRET: ENC[AES256_GCM,data:u4BUJRVjxlYMJSOiZ7LO92nRxwROsi5YAm1y0XsEbdIT,iv:7/cLWv7t+QpR7o9PWCoqVw01K5PMrOKsMLYqXycqly4=,tag:wVMh+X0Bd3ywYV1NYhgoyQ==,type:str]
            JWT_REFRESH_SECRET: ENC[AES256_GCM,data:+AS6Uz5g499X2y03pgQiAYoVpfZJy30sC0j2oPGJ5sCE,iv:DOI7iBP/CSxMv76gR2GbTbP0DPxORHJUaz0Mk1biEPw=,tag:tZMknm9WykKSqNowkQuQ2g==,type:str]
            MEILI_MASTER_KEY: ENC[AES256_GCM,data:JrEvH30VlqmZero1I0q0JJ8cotjgLr7KtdiCWW93z1cW,iv:2uXBaqeWNMiq1teaLezPbgBtClQ47v8x5klpFk7wmiE=,tag:5uUKXnWYHjkFPJKSnJHBew==,type:str]
            MONGO_ROOT_PASSWORD: ENC[AES256_GCM,data:H6AU/3jNuKuawXFE0CS0rjDqvzR11f2IOrePxg==,iv:ybtgC3CFZj+e7oneT0ZbQaDLmyYgkRgX2QDO1T4US+4=,tag:fAzAlTxzDFlQl+mPApKdUQ==,type:str]
            REDIS_PASSWORD: ENC[AES256_GCM,data:QpBlX7AjF+4pVHWP/STehhfKeS4GlZOpr9bsxg==,iv:iCTGLurHEIy0999Zkh/2w+n2AKVIcV2LMYmuIrJaZRQ=,tag:RdItBDpvBbGWLHnsPK4d9w==,type:str]
            OPENAI_API_KEY: ENC[AES256_GCM,data:VKTfqklH5QyawIOAhhzplIuzT306,iv:oL14eVmJwVb/1alT18BTXGO+6Idp70MlOYKIchfvsKQ=,tag:qxjboaVzMOrruPq+fhc/VA==,type:str]
            ANTHROPIC_API_KEY: ENC[AES256_GCM,data:kxo8sjT4HOqyfAOS/KpAuSB94VeN/fPv,iv:v65pAnfk2naQpKxO/M9ERU6KemmOBvskwNjUuFmdo4o=,tag:Wnt2TosUiLid8bte8050DQ==,type:str]
sops:
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUDM2azVaa0FSa2Jpc0ds
            WjJ0TGVyd2h3VEVFV0VxWlM2aVBoaVJsT3pnClZ1UnQxYVhVVEI0MWZiTGVNZ1lL
            WUJZZ0Z6ZC9qcDZQVHI4MTlOeUNNSXcKLS0tIG5yTVZCQXQ2a1laSyt1WGUxV3A0
            QXBibXd1blUvcG4zaTVBZHFOQXF1K28K3XMiyS190l++6vZ9e+eLc5agDZqGa6Wk
            PosRsBCW4dqC7FCqZD+npsvXGxcJSBi4Z8/tVBe+M60Qn3IJqpwf/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T20:11:58Z"
    mac: ENC[AES256_GCM,data:23TEY3hYJt2BKF9l19u1cprvc3FK2rfiBllOH22ZLm6HYie0MXRb9xjBw2HMHcHJS7olwU1qTVQVgZnPatZnlYoBZWuMSi4KVFwF4CZD63wEVJ4MCLQIve5Wh2+G2FMBztv3KWPFh4CtfSjgbDWIBlsgmdyXKQR6uF+GhxUJEDk=,iv:bxeLLNR6Jdn5/c6gmK4OrOirkOkz5WxL8Jc2aKOlsr8=,tag:o0xsMtIEemW7ipHJcZl1gA==,type:str]
    encrypted_suffix: Templates
    version: 3.12.1
