apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: searxng
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/trueforge-org/truecharts.git
    targetRevision: HEAD
    path: charts/stable/searxng
    helm:
      valueFiles:
        - values.yaml
      # Optional: if you want to override values inline instead of file, use `values` block
  destination:
    server: https://kubernetes.default.svc
    namespace: searxng
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
