apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
spec:
  project: default
  sources:
    - chart: cluster-autoscaler
      repoURL: https://kubernetes.github.io/autoscaler
      targetRevision: 9.46.6
      helm:
        releaseName: cluster-autoscaler
        valueFiles:
          - $repo/devops/argocd/cluster-autoscaler/values.yaml
    - repoURL: 'https://github.com/hnatekmarorg/devops-cluster.git'
      targetRevision: main
      ref: repo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false