# https://raw.githubusercontent.com/kubernetes/autoscaler/refs/heads/master/charts/cluster-autoscaler/values.yaml
cloudProvider: clusterapi
clusterAPIKubeconfigSecret: mgmt-cluster
clusterAPIMode: incluster-kubeconfig
clusterAPICloudConfigPath: /etc/kubernetes/mgmt-kubeconfig/kubeconfig
extraVolumeMounts:
  - name: cluster-api-kubeconfig
    mountPath: /etc/kubernetes/mgmt-kubeconfig
    readOnly: true
autoDiscovery:
  clusterName: main