apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: storage
  namespace: longhorn-system
spec:
  disks:
    sdb:
      path: /var/mnt/sdb
      allowScheduling: true
      tags:
        - "hdd"
    sdc:
      path: /var/mnt/sdc
      allowScheduling: true
      tags:
        - "hdd"
    sdd:
      path: /var/mnt/sdd
      allowScheduling: true
      tags:
        - "hdd"
