---
# AppRole role as we intend it for production: short TTLs, single-use SecretIDs.
apiVersion: approle.vault.upbound.io/v1alpha1
kind: AuthBackendRole
metadata:
  name: atuin-ro
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  providerConfigRef:
    name: bao-staging
  forProvider:
    backendRef:
      name: approle
    roleName: atuin-ro
    tokenPolicies:
      - atuin-ro
    tokenTtl: 3600
    tokenMaxTtl: 7200
    tokenType: service
    bindSecretId: true
    secretIdNumUses: 1
    secretIdTtl: 600
