apiVersion: v1
kind: Namespace
metadata:
  name: velero
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: default
  source:
    chart: velero
    repoURL: https://vmware-tanzu.github.io/helm-charts/
    targetRevision: 10.0.1
    helm:
      releaseName: velero
  destination:
    server: "https://kubernetes.default.svc"
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
---
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: minio-backup
  namespace: velero
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider: aws
  objectStorage:
    bucket: main-velero-backup
  config:
    region: minio
    s3ForcePathStyle: "true"
    s3Url: "https://minio.hnatekmar.xyz"