prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 25Gi
grafana:
  grafana.ini:
    server:
      root_url: https://grafana.hnatekmar.dev
  ingress:
    enabled: true
    hosts:
      - grafana.hnatekmar.dev
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-cloudflare
      kubernetes.io/ingress.class: nginx
    tls:
    - secretName: grafana-tls
      hosts:
        - grafana.hnatekmar.dev
crds:
  enabled: true
  upgradeJob:
    enabled: true
