apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: disk-manager
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: disk-manager
  template:
    metadata:
      labels:
        app: disk-manager
    spec:
      volumes:
        - name: var
          hostPath:
            path: /var
      hostNetwork: true
      tolerations:
        - key: "node-role.talos.dev/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "CriticalAddonsOnly"
          operator: "Exists"
      containers:
        - name: disk-tools
          image: alpine:latest
          volumeMounts:
            - mountPath: /var
              name: var
          securityContext:
            privileged: true
            runAsUser: 0
          command: ["/bin/sh", "-c", "apk add git git-lfs parted iputils parted iperf util-linux sgdisk lsblk && sleep infinity"]
