apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: model-downloader
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: model-downloader
  template:
    metadata:
      labels:
        app: model-downloader
    spec:
      volumes:
        - name: nas
          nfs:
            server: 192.168.88.25
            path: /mnt/data/k8s
      hostNetwork: true
      tolerations:
        - key: "node-role.talos.dev/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "CriticalAddonsOnly"
          operator: "Exists"
      containers:
        - name: disk-tools
          image: alpine:latest
          volumeMounts:
            - mountPath: /mnt/data/k8s
              name: nas
          securityContext:
            privileged: true
            runAsUser: 0
          command: ["/bin/sh", "-c", "apk add git git-lfs && sleep infinity"]
