apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: init
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 1.12.2
    helm:
      releaseName:
      valueFiles:
        - $repo/devops/argocd/nginx/values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
