apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: 2024.10.0
    helm:
      releaseName: authentik
      values: |
        global:
          envFrom:
            - secretRef:
                name: authentik-cookie
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-postgresql
                  key: password
        authentik:
          secret_key: env://SECRET_KEY
          postgresql:
            password: env://POSTGRES_PASSWORD
        server:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-cloudflare
            hosts:
              - authentik.hnatekmar.dev
            tls:
              - secretName: authentik-hnatekmar
                hosts:
                  - authentik.hnatekmar.dev
        postgresql:
          enabled: true
          persistence:
            storageClass: longhorn
        redis:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true