apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: init
  namespace: argocd
  labels:
    name: init
spec:
  project: default
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - Validate=false
    automated:
      selfHeal: true
  source:
    directory:
      recurse: true
    repoURL: https://github.com/hnatekmarorg/devops-cluster.git
    targetRevision: HEAD
    path: devops/argocd
