apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llama-cpp
  namespace: argocd  # or your Argo CD namespace
spec:
  project: default
  ignoreDifferences:
    - kind: "*"
      group: "*"
      namespace: inference
      jsonPointers:
        - /spec/replicas
  sources:
    - name: chart
      repoURL: https://github.com/hnatekmarorg/devops-cluster.git
      path: charts/llama-cpp
      targetRevision: main
      helm:
        valuesObject:
          models:
            - name: exl
              cooldownPeriod: 3600
              engine: tabby
              replicas: 1
              resources:
                requests:
                  nvidia.com/gpu: 6
                limits:
                  nvidia.com/gpu: 6
              args:
                - main.py
                - --host
                - "0.0.0.0"
                - --port
                - "8080"
                - --model-dir
                - /models/exl2
                - --inline-model-loading
                - "true"
                - --disable-auth
                - "true"
            - name: cogito
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 6
                limits:
                  nvidia.com/gpu: 6
              args:
                - --jinja
                - -c
                - "256000" 
                - --temp
                - "0.6"
                - --top-p
                - "0.9"
                - --min-p
                - "0.01"
                - --no-mmproj
                - --no-mmap
                - --model
                - "/models/gguf/cogito/cogito-v2-preview-llama-109B-MoE-UD-Q6_K_XL-00001-of-00002.gguf"
                - "-ngl"
                - "99"
                - -fa
                - "on"
                - -t
                - "-1"
                - --prio
                - "3"
                - --jinja
                - --numa
                - distribute
                - --alias
                - "cogito"
            - name: gpt-oss
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 4
                limits:
                  nvidia.com/gpu: 4
              args:
                - --jinja
                - -c
                - "131072" 
                - --temp
                - "1.0"
                - --top-p
                - "1"
                - --top-k
                - "0"
                - --no-mmap
                - --model
                - "/models/gguf/gpt-oss/gpt-oss-120b-UD-Q8_K_XL-00001-of-00002.gguf"
                - "-ngl"
                - "99"
                - -fa
                - "on"
                - -t
                - "-1"
                - --prio
                - "3"
                - --jinja
                - --chat-template-kwargs 
                - '{"reasoning_effort": "high"}'
                - --numa
                - distribute
                - --alias
                - "gpt-oss"
                
            - name: gpt-oss-20b
              engine: vllm
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 1
                limits:
                  nvidia.com/gpu: 1
              args:
                - /models/fp8/gpt-oss-20b
                - --async-scheduling
                - --tool-call-parser 
                - openai
                - --enable-auto-tool-choice
                - --served-model-name
                - gpt-oss-20b
            - name: gemma3
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 2
                limits:
                  nvidia.com/gpu: 2
              args:
                - --yarn-orig-ctx
                - "32768"
                - --temp
                - "1.0"
                - --top-p
                - "0.95"
                - --top-k
                - "64"
                - --no-mmap
                - --jinja
                - --mmproj
                - "/models/gguf/gemma3/mmproj-F16.gguf"
                - "-m"
                - "/models/gguf/gemma3/gemma-3-27b-it-UD-Q8_K_XL.gguf"
                - "-ngl"
                - "99"
                - -fa
                - "on"
                - -t
                - "-1"
                - --jinja
                - --prio
                - "3"
                - --numa
                - distribute
                - --alias
                - gemma3
            - name: behemoth
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 6
                limits:
                  nvidia.com/gpu: 6
              args:
                - --ctx-size
                - "131072"
                - --no-mmap
                - "-m"
                - "/models/gguf/behemoth/q_4/TheDrummer_Behemoth-R1-123B-v2-Q4_K_M-00001-of-00002.gguf"
                - "-ngl"
                - "99"
                - -t
                - "-1"
                - --prio
                - "3"
                - --numa
                - distribute
                - --alias
                - "behemoth"
            - name: behemoth-redux
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 6
                limits:
                  nvidia.com/gpu: 6
              args:
                - --ctx-size
                - "64000"
                - --no-mmap
                - "-m"
                - "/models/gguf/behemoth-redux/TheDrummer_Behemoth-ReduX-123B-v1-Q6_K-00001-of-00003.gguf"
                - "-ngl"
                - "99"
                - -t
                - "-1"
                - --prio
                - "3"
                - --numa
                - distribute
                - --alias
                - "behemoth-redux"

            - name: qwen3-30b-thinking
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 3
                limits:
                  nvidia.com/gpu: 3
              args:
                - --alias
                - "qwen3-30b-thinking"
                - --temp
                - "0.7"
                - --min-p
                - "0.0"
                - --top-p
                - "0.8"
                - --top-k
                - "20"
                - -t
                - "-1"
                - --jinja
                - --ctx-size
                - "262144"
                - -fa
                - "on"
                - --numa
                - distribute
                - -m
                - /models/gguf/Qwen3-30B-A3B-Thinking-2507-UD-Q8_K_XL.gguf
            - name: qwen3-30b-coder
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 2
                limits:
                  nvidia.com/gpu: 2
              args:
               - -ngl 
               - "99"
               - -m 
               - /models/gguf/Qwen3-Coder-30B-A3B-Instruct-UD-Q6_K_XL.gguf
               - -fa 
               - "on"
               - --no-mmap 
               - --ctx-size 
               - "182500" 
               - --jinja 
               - --alias 
               - qwen3-coder-30b
               - --temp 
               - "0.7"
               - --top-p 
               - "0.8"
               - --top-k
               - "20"
               - --repeat-penalty
               - "1.05"
            - name: llama-3-3-nemotron-super
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 3
                limits:
                  nvidia.com/gpu: 3
              args:
               - -ngl 
               - "99"
               - -m 
               - /models/gguf/nemotron/Llama-3_3-Nemotron-Super-49B-v1_5-UD-Q6_K_XL.gguf 
               - -fa 
               - "on"
               - --no-mmap 
               - --ctx-size 
               - "100000"
               - -sm 
               - row  
               - --jinja 
               - --alias 
               - llama-3-3-nemotron-super
               - --temp 
               - "0.6"
               - --top-p 
               - "0.95"
            - name: glm-4-5-air
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 6
                limits:
                  nvidia.com/gpu: 6
              args:
                - --jinja
                - -c
                - "128000" 
                - --temp
                - "0.6"
                - --top-p
                - "0.95"
                - --top-k
                - "40"
                - --no-mmap
                - --model
                - "/models/gguf/glm-air/GLM-4.5-Air-Q6_K-00001-of-00002.gguf"
                - "-ngl"
                - "99"
                - -fa
                - "on"
                - -t
                - "-1"
                - --prio
                - "3"
                - --jinja
                - --numa
                - distribute
                - --alias
                - "glm-4-5-air"
            - name: qwen3-30b-instruct
              engine: vllm
              cooldownPeriod: 7200
              resources:
                requests:
                  nvidia.com/gpu: 3
                limits:
                  nvidia.com/gpu: 3
              args:
                - --pipeline-parallel-size
                - "3"
                - --port
                - "8080"
                - /models/fp8/Qwen3-30B-A3B-Instruct-2507-FP8/
                - --enable-auto-tool-choice 
                - --tool-call-parser
                - hermes
                - --served-model-name
                - qwen3-30b-instruct
                - --enable-expert-parallel
            - name: qwen2-32b-vl
              engine: vllm
              cooldownPeriod: 7200
              resources:
                requests:
                  nvidia.com/gpu: 3
                limits:
                  nvidia.com/gpu: 3
              args:
                - --pipeline-parallel-size=3
                - --port
                - "8080"
                - --model
                - /models/awq/Qwen2.5-VL-32B-Instruct-AWQ
                - --served-model-name
                - qwen2-32b-vl
                - --limit-mm-per-prompt 
                - "image=8"            
            - name: qwen2-7b-vl
              engine: vllm
              cooldownPeriod: 7200
              resources:
                requests:
                  nvidia.com/gpu: 1
                limits:
                  nvidia.com/gpu: 1
              args:
                - --port
                - "8080"
                - --model
                - /models/fp8/Qwen2.5-VL-7B-Instruct
                - --served-model-name
                - qwen2-7b-vl
                - --limit-mm-per-prompt.image 
                - "8"

  destination:
    server: https://kubernetes.default.svc
    namespace: inference
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
