apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llama-cpp
  namespace: argocd  # or your Argo CD namespace
spec:
  project: default
  ignoreDifferences:
    - kind: "*"
      group: "*"
      namespace: inference
      jsonPointers:
        - /spec/replicas
  sources:
    - name: chart
      repoURL: https://github.com/hnatekmarorg/devops-cluster.git
      path: charts/llama-cpp
      targetRevision: main
      helm:
        valuesObject:
          models:

            - name: qwen-coder-exl2
              engine: tabby
              replicas: 1
              resources:
                requests:
                  nvidia.com/gpu: 2
                limits:
                  nvidia.com/gpu: 2
              args:
                - main.py
                - --host
                - "0.0.0.0"
                - --port
                - "8080"
                - --cuda-malloc-backend
                - "true"
                - --max-seq-len 
                - "32768"
                - --cache-mode
                - "Q8" 
                - --draft-model-dir
                - /models/exl2
                - --draft-model-name
                - Qwen2.5-Coder-0.5B-Instruct-exl2_5.0bpw
                - --model-dir
                - /models/exl2
                - --model-name
                - Qwen2.5-Coder-32B-Instruct-exl2
                - --disable-auth
                - "true"
              cooldownPeriod: 600
            - name: scout
              cooldownPeriod: 600
              resources:
                requests:
                  nvidia.com/gpu: 4
                limits:
                  nvidia.com/gpu: 4
              args:
                - -ot 
                - ".ffn_.*_exps.=CPU"
                - --no-mmap
                - --jinja
                - "-m"
                - "/models/gguf/scout/Llama-4-Scout-17B-16E-Instruct-UD-Q4_K_XL-00001-of-00002.gguf"
                - "-ngl"
                - "99"
                - -fa
                - --cache-type-k
                - "q8_0"
                - --cache-type-v
                - "q8_0"
                - -t
                - "-1"
                - --jinja
                - --prio
                - "3"
                - --temp
                - "0.6"
                - --min-p
                - "0.01"
                - --top-p
                - "0.9"
                - --ctx-size 
                - "2000000"
                - --mmproj
                - /models/gguf/scout/mmproj-F16.gguf
                - --numa
                - distribute
                - --alias
                - "scout"
            - name: athene-agent
              cooldownPeriod: 600
              resources:
                requests:
                  nvidia.com/gpu: 4
                limits:
                  nvidia.com/gpu: 4
              args:
                - --jinja
                - "-m"
                - "/models/gguf/athene-v2-agent/Athene-V2-Agent-Q6_K_L-00001-of-00002.gguf"
                - "-ngl"
                - "99"
                - -fa
                - --cache-type-k
                - "q8_0"
                - --cache-type-v
                - "q8_0"
                - -t
                - "-1"
                - --jinja
                - --temp
                - "0"
                - --ctx-size 
                - "32768"
                - --numa
                - distribute
                - --alias
                - "athene-agent"
                - --top_p
                - "0"
                - --top_k
                - "0"
              selector: { }
              resources:
                requests:
                  nvidia.com/gpu: 4
                limits:
                  nvidia.com/gpu: 4


            - name: qwen3-32b-exl # exl2 example
              engine: tabby
              replicas: 1
              cooldownPeriod: 600
              resources:
                requests:
                  nvidia.com/gpu: 2
                limits:
                  nvidia.com/gpu: 2
              args:
                - main.py
                - --host
                - "0.0.0.0"
                - --port
                - "8080"
                - --cuda-malloc-backend
                - "true"
                - --cache-mode
                - "Q8" 
                - --max-seq-len 
                - "32768"
                - --model-dir
                - /models/exl2
                - --model-name
                - "Qwen3-32B-exl3"
                - --disable-auth
                - "true"

            - name: qwen3-235b-q8
              args:
                - --jinja
                - -c
                - "32768"
                - -ngl
                - "99"
                - --no-mmap
                - --flash-attn
                - --numa
                - distribute
                - --override-tensor
                - blk\.[0-9][0-7]?\.ffn.*exps.*=CPU
                - -m
                - /models/gguf/Qwen-235B/Qwen3-235B-A22B-128K-UD-Q8_K_XL-00001-of-00006.gguf
              selector: { }
              resources:
                requests:
                  memory: "300Gi"
                limits:
                  memory: "300Gi"

            - name: qwen3-32b
              args:
                - --jinja
                - "-m"
                - "/models/gguf/Qwen3-32B-Q5_K_M.gguf"
                - "-ngl"
                - "99"
              selector: { }
              resources:
                requests:
                  nvidia.com/gpu: 2
                limits:
                  nvidia.com/gpu: 2
            - name: forgotten
              engine: tabby
              cooldownPeriod: 600
              args:
                - main.py
                - --host
                - "0.0.0.0"
                - --port
                - "8080"
                - --cuda-malloc-backend
                - "true"
                - --max-seq-len 
                - "128000"
                - --cache-mode
                - "Q8" 
                - --model-dir
                - /models/exl2
                - --model-name
                - forgotten
                - --disable-auth
                - "true"
              selector: { }
              resources:
                requests:
                  nvidia.com/gpu: 4
                limits:
                  nvidia.com/gpu: 4
  destination:
    server: https://kubernetes.default.svc
    namespace: inference
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
