apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llama-cpp
  namespace: argocd  # or your Argo CD namespace
spec:
  project: default
  ignoreDifferences:
    - kind: "*"
      group: "*"
      namespace: inference
      jsonPointers:
        - /spec/replicas
  sources:
    - name: chart
      repoURL: https://github.com/hnatekmarorg/devops-cluster.git
      path: charts/llama-cpp
      targetRevision: main
      helm:
        valuesObject:
          models:
            - name: exl
              cooldownPeriod: 3600
              engine: tabby
              replicas: 1
              resources:
                requests:
                  nvidia.com/gpu: 6
                limits:
                  nvidia.com/gpu: 6
              args:
                - main.py
                - --host
                - "0.0.0.0"
                - --port
                - "8080"
                - --model-dir
                - /models/exl2
                - --inline-model-loading
                - "true"
                - --disable-auth
                - "true"
            - name: gpt-oss
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 4
                limits:
                  nvidia.com/gpu: 4
              args:
                - --jinja
                - -c
                - "120000" 
                - --temp
                - "1.0"
                - --top-p
                - "1"
                - --top-k
                - "0"
                - --no-mmap
                - --model
                - "/models/gguf/gpt-oss/gpt-oss-120b-UD-Q8_K_XL-00001-of-00002.gguf"
                - "-ngl"
                - "99"
                - -fa
                - "on"
                - -t
                - "-1"
                - --prio
                - "3"
                - --jinja
                - --chat-template-kwargs 
                - '{"reasoning_effort": "high"}'
                - --numa
                - distribute
                - --alias
                - "gpt-oss"
            - name: qwen3-32b
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 3
                limits:
                  nvidia.com/gpu: 3
              args:
                - --alias
                - "qwen3-32b"
                - --temp
                - "0.6"
                - --min-p
                - "0.0"
                - --top-p
                - "0.95"
                - --top-k
                - "20"
                - -t
                - "-1"
                - --jinja
                - --ctx-size
                - "32768"
                - -fa
                - "on"
                - --numa
                - distribute
                - -m
                - /models/gguf/Qwen3-32B-128K-UD-Q8_K_XL.gguf
            - name: gemma3
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 2
                limits:
                  nvidia.com/gpu: 2
              args:
                - --yarn-orig-ctx
                - "32768"
                - --temp
                - "1.0"
                - --top-p
                - "0.95"
                - --top-k
                - "64"
                - --no-mmap
                - --jinja
                - --mmproj
                - "/models/gguf/gemma3/mmproj-F16.gguf"
                - "-m"
                - "/models/gguf/gemma3/gemma-3-27b-it-UD-Q8_K_XL.gguf"
                - "-ngl"
                - "99"
                - -fa
                - "on"
                - -t
                - "-1"
                - --jinja
                - --prio
                - "3"
                - --numa
                - distribute
                - --alias
                - gemma3
            - name: behemoth
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 6
                limits:
                  nvidia.com/gpu: 6
              args:
                - --ctx-size
                - "131072"
                - --no-mmap
                - "-m"
                - "/models/gguf/behemoth/q_4/TheDrummer_Behemoth-R1-123B-v2-Q4_K_M-00001-of-00002.gguf"
                - "-ngl"
                - "99"
                - -t
                - "-1"
                - --prio
                - "3"
                - --numa
                - distribute
                - --alias
                - "behemoth"
            - name: glm-steam
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 6
                limits:
                  nvidia.com/gpu: 6
              args:
                - --ctx-size
                - "128000"
                - --temp
                - "0.6"
                - --top-p
                - "0.8"
                - --top-k
                - "20"
                - --no-mmap
                - --jinja
                - "-m"
                - "/models/gguf/glm-steam/TheDrummer_GLM-Steam-106B-A12B-v1-Q6_K-00001-of-00003.gguf"
                - "-ngl"
                - "99"
                - -fa
                - -t
                - "-1"
                - --jinja
                - --prio
                - "3"
                - --numa
                - distribute
                - --alias
                - "glm-steam"
            - name: qwen3-30b-thinking
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 3
                limits:
                  nvidia.com/gpu: 3
              args:
                - --alias
                - "qwen3-30b-thinking"
                - --temp
                - "0.7"
                - --min-p
                - "0.0"
                - --top-p
                - "0.8"
                - --top-k
                - "20"
                - -t
                - "-1"
                - --jinja
                - --ctx-size
                - "262144"
                - -fa
                - "on"
                - --numa
                - distribute
                - -m
                - /models/gguf/Qwen3-30B-A3B-Thinking-2507-UD-Q8_K_XL.gguf
            - name: qwen3-30b-instruct
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 3
                limits:
                  nvidia.com/gpu: 3
              args:
                - --alias
                - "qwen3-30b-instruct"
                - --temp
                - "0.7"
                - --min-p
                - "0.0"
                - --top-p
                - "0.8"
                - --top-k
                - "20"
                - -t
                - "-1"
                - --jinja
                - --ctx-size
                - "125000"
                - -fa
                - "on"
                - --numa
                - distribute
                - -m
                - /models/gguf/Qwen_Qwen3-30B-A3B-Instruct-2507-Q8_0.gguf
            - name: hunyuan-a13b-instruct
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 6
                limits:
                  nvidia.com/gpu: 6
              args:
                - --alias
                - "hunyuan-a13b-instruct"
                - --temp
                - "0.7"
                - --min-p
                - "0.05"
                - --top-p
                - "0.8"
                - --top-k
                - "20"
                - --repeat-penalty
                - "1.05"
                - -t
                - "-1"
                - --jinja
                - --ctx-size
                - "262144"
                - -fa
                - "on"
                - --numa
                - distribute
                - -m
                - /models/gguf/hyunyuan/Hunyuan-A13B-Instruct-UD-Q8_K_XL-00002-of-00002.gguf
            - name: qwen3-235b-instruct
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 6
                limits:
                  nvidia.com/gpu: 6
              args:
                - --alias
                - "qwen3-235b-instruct"
                - --temp
                - "0.6"
                - --min-p
                - "0.0"
                - --top-p
                - "0.95"
                - --top-k
                - "20"
                - --presence-penalty
                - "1.0"
                - -t
                - "-1"
                - --jinja
                - --ctx-size
                - "125000"
                - -fa
                - "on"
                - --numa
                - distribute
                - -m
                - /models/gguf/Qwen3-235B-A22B-2507/Qwen3-235B-A22B-Instruct-2507-UD-Q3_K_XL-00001-of-00003.gguf
            - name: qwen3-235b-thinking
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 6
                limits:
                  nvidia.com/gpu: 6
              args:
                - --alias
                - "qwen3-235b-thinking"
                - --temp
                - "0.6"
                - --min-p
                - "0.0"
                - --top-p
                - "0.95"
                - --top-k
                - "20"
                - --presence-penalty
                - "1.0"
                - -t
                - "-1"
                - --jinja
                - --ctx-size
                - "125000"
                - -fa
                - "on"
                - --numa
                - distribute
                - -m
                - /models/gguf/Qwen3-235B-A22B-2507/Qwen3-235B-A22B-Thinking-2507-UD-Q3_K_XL-00001-of-00003.gguf
              selector: { }
              cpuResources:
                requests:
                  memory: "300Gi"
                limits:
                  memory: "300Gi"
            - name: glm-4-5-air
              engine: vllm
              cooldownPeriod: 7200
              resources:
                requests:
                  nvidia.com/gpu: 6
                limits:
                  nvidia.com/gpu: 6
              args:
                - --pipeline-parallel-size
                - "6"
                - --port
                - "8080"
                - --trust-remote-code
                - --model
                - /models/awq/GLM-4.5-Air-AWQ-FP16Mix
                - --served-model-name
                - glm-4-5-air
                - --tool-call-parser
                - glm45
                - --reasoning-parser
                - glm45
                - --enable-auto-tool-choice
                - --enable-expert-parallel
            - name: qwen3-coder
              engine: vllm
              cooldownPeriod: 7200
              resources:
                requests:
                  nvidia.com/gpu: 4
                limits:
                  nvidia.com/gpu: 4
              args:
                - --tensor-parallel-size=4
                - --port
                - "8080"
                - --model
                - /models/fp8/Qwen3-Coder-30B-A3B-Instruct
                - --served-model-name
                - qwen3-coder-plus
                - --enable-auto-tool-choice
                - --tool-call-parser
                - qwen3_coder
                - --enable-expert-parallel
  destination:
    server: https://kubernetes.default.svc
    namespace: inference
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
