apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llama-cpp
  namespace: argocd  # or your Argo CD namespace
spec:
  project: default
  ignoreDifferences:
    - kind: "*"
      group: "*"
      namespace: inference
      jsonPointers:
        - /spec/replicas
  sources:
    - name: chart
      repoURL: https://github.com/hnatekmarorg/devops-cluster.git
      path: charts/llama-cpp
      targetRevision: main
      helm:
        valuesObject:
          models:
            - name: qwen-coder-14b
              engine: vllm
              replicas: 1
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 1
                limits:
                  nvidia.com/gpu: 1
              args:
                - --max-model-len 
                - "32768" 
                - --tensor-parallel-size
                - "1"
                - --host
                - "0.0.0.0"
                - --port
                - "8080"
                - --model
                - /models/awq/Qwen2.5-Coder-14B-Instruct-AWQ
            - name: qwen-72b-awq
              engine: vllm
              replicas: 1
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 4
                limits:
                  nvidia.com/gpu: 4
              args:
                - --kv-cache-dtype
                - fp8
                - --hf-overrides 
                - '{"rope_scaling":{"factor":4,"original_max_position_embeddings":32768,"type":"yarn","rope_type":"yarn"}}' 
                - --max-model-len 
                - "52000" 
                - --tensor-parallel-size
                - "4"
                - --host
                - "0.0.0.0"
                - --port
                - "8080"
                - --model
                - /models/awq/Qwen2.5-VL-72B-Instruct-AWQ
            - name: qwen-coder-exl2
              engine: tabby
              replicas: 1
              resources:
                requests:
                  nvidia.com/gpu: 2
                limits:
                  nvidia.com/gpu: 2
              args:
                - main.py
                - --host
                - "0.0.0.0"
                - --port
                - "8080"
                - --cuda-malloc-backend
                - "true"
                - --max-seq-len 
                - "32768"
                - --cache-mode
                - "Q8" 
                - --draft-model-dir
                - /models/exl2
                - --draft-model-name
                - Qwen2.5-Coder-0.5B-Instruct-exl2_5.0bpw
                - --model-dir
                - /models/exl2
                - --model-name
                - Qwen2.5-Coder-32B-Instruct-exl2
                - --disable-auth
                - "true"
              cooldownPeriod: 600
            - name: qwen-72b
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 5
                limits:
                  nvidia.com/gpu: 5
              args:
                - --rope-scaling 
                - yarn 
                - --rope-scale
                - "4"
                - --yarn-orig-ctx
                - "32768"
                - --temp
                - "0.7"
                - --top-p
                - "0.8"
                - --top-k
                - "20"
                - --no-mmap
                - --jinja
                - --mmproj
                - "/models/gguf/Qwen-72B/mmproj-Qwen2-VL-72B-Instruct-f32.gguf"
                - "-m"
                - "/models/gguf/Qwen-72B/Qwen2.5-VL-72B-Instruct-UD-Q6_K_XL-00001-of-00002.gguf"
                - "-ngl"
                - "99"
                - -fa
                - --cache-type-k
                - "q8_0"
                - --cache-type-v
                - "q8_0"
                - -c
                - "131072"
                - -t
                - "-1"
                - --jinja
                - --prio
                - "3"
                - --numa
                - distribute
                - --alias
                - "qwen-72b"
            - name: forgotten
              cooldownPeriod: 600
              resources:
                requests:
                  nvidia.com/gpu: 5
                limits:
                  nvidia.com/gpu: 5
              args:
                - --no-mmap
                - --jinja
                - "-m"
                - "/models/gguf/forgotten/Forgotten-Safeword-70B-v5.0.Q8_0.gguf"
                - "-ngl"
                - "99"
                - -fa
                - -t
                - "-1"
                - --jinja
                - --prio
                - "3"
                - --ctx-size 
                - "64000"
                - --numa
                - distribute
                - --alias
                - "forgotten"
            - name: fallen-command
              cooldownPeriod: 600
              resources:
                requests:
                  nvidia.com/gpu: 5
                limits:
                  nvidia.com/gpu: 5
              args:
                - --no-mmap
                - --jinja
                - "-m"
                - "/models/gguf/fallen-command/TheDrummer_Fallen-Command-A-111B-v1.1-Q5_K_S-00001-of-00002.gguf"
                - "-ngl"
                - "99"
                - -fa
                - --cache-type-k
                - "q8_0"
                - --cache-type-v
                - "q8_0"
                - -t
                - "-1"
                - --jinja
                - --prio
                - "3"
                - --ctx-size 
                - "256000"
                - --numa
                - distribute
                - --alias
                - "fallen-command"
            - name: scout
              cooldownPeriod: 600
              resources:
                requests:
                  nvidia.com/gpu: 5
                limits:
                  nvidia.com/gpu: 5
              args:
                - --no-mmap
                - --jinja
                - "-m"
                - "/models/gguf/scout/Llama-4-Scout-17B-16E-Instruct-UD-Q4_K_XL-00001-of-00002.gguf"
                - "-ngl"
                - "99"
                - -fa
                - --cache-type-k
                - "q8_0"
                - --cache-type-v
                - "q8_0"
                - -t
                - "-1"
                - --jinja
                - --prio
                - "3"
                - --temp
                - "0.6"
                - --min-p
                - "0.01"
                - --top-p
                - "0.9"
                - --ctx-size 
                - "32000"
                - --mmproj
                - /models/gguf/scout/mmproj-F16.gguf
                - --numa
                - distribute
                - --alias
                - "scout"
            - name: qwen3-32b-exl # exl2 example
              engine: tabby
              replicas: 1
              cooldownPeriod: 600
              resources:
                requests:
                  nvidia.com/gpu: 2
                limits:
                  nvidia.com/gpu: 2
              args:
                - main.py
                - --host
                - "0.0.0.0"
                - --port
                - "8080"
                - --cuda-malloc-backend
                - "true"
                - --cache-mode
                - "Q8" 
                - --max-seq-len 
                - "32768"
                - --model-dir
                - /models/exl2
                - --model-name
                - "Qwen3-32B-exl3"
                - --disable-auth
                - "true"

            - name: qwen3-235b-q8
              args:
                - --jinja
                - -c
                - "32768"
                - -ngl
                - "0"
                - --no-mmap
                - --flash-attn
                - --numa
                - distribute
                - --override-tensor
                - blk\.[0-9][0-7]?\.ffn.*exps.*=CPU
                - -m
                - /models/gguf/Qwen-235B/Qwen3-235B-A22B-128K-UD-Q8_K_XL-00001-of-00006.gguf
              selector: { }
              resources:
                requests:
                  memory: "300Gi"
                limits:
                  memory: "300Gi"
  destination:
    server: https://kubernetes.default.svc
    namespace: inference
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
