apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llama-cpp
  namespace: argocd  # or your Argo CD namespace
spec:
  project: default
  ignoreDifferences:
    - kind: "*"
      group: "*"
      namespace: inference
      jsonPointers:
        - /spec/replicas
  sources:
    - name: chart
      repoURL: https://github.com/hnatekmarorg/devops-cluster.git
      path: charts/llama-cpp
      targetRevision: main
      helm:
        valuesObject:
          models:
            - name: exl
              cooldownPeriod: 3600
              engine: tabby
              replicas: 1
              resources:
                requests:
                  nvidia.com/gpu: 4
                limits:
                  nvidia.com/gpu: 4
              args:
                - main.py
                - --host
                - "0.0.0.0"
                - --port
                - "8080"
                - --cuda-malloc-backend
                - "true"
                - --model-dir
                - /models/exl2
                - --inline-model-loading
                - "true"
                - --disable-auth
                - "true"
            - name: gpt-oss
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 4
                limits:
                  nvidia.com/gpu: 4
              args:
                - --jinja
                - -c
                - "131072" 
                - --temp
                - "1.0"
                - --top-p
                - "1"
                - --top-k
                - "0"
                - --no-mmap
                - --model
                - "/models/gguf/gpt-oss/gpt-oss-120b-UD-Q8_K_XL-00001-of-00002.gguf"
                - "-ngl"
                - "99"
                - -fa
                - -t
                - "-1"
                - --prio
                - "3"
                - --jinja
                - --chat-template-kwargs 
                - '{"reasoning_effort": "high"}'
                - --numa
                - distribute
                - --alias
                - "gpt-oss"
            - name: gemma3
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 1
                limits:
                  nvidia.com/gpu: 1
              args:
                - --yarn-orig-ctx
                - "32768"
                - --temp
                - "1.0"
                - --top-p
                - "0.95"
                - --top-k
                - "64"
                - --no-mmap
                - --jinja
                - --mmproj
                - "/models/gguf/gemma3/mmproj-mlabonne_gemma-3-27b-it-abliterated-f16.gguf"
                - "-m"
                - "/models/gguf/gemma3/gemma-3-27b-it-abliterated.q6_k.gguf"
                - "-ngl"
                - "99"
                - -fa
                - -t
                - "-1"
                - --jinja
                - --prio
                - "3"
                - --numa
                - distribute
                - --alias
                - gemma3
            - name: behemoth
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 5
                limits:
                  nvidia.com/gpu: 5
              args:
                - --ctx-size
                - "64000"
                - --no-mmap
                - --jinja
                - "-m"
                - "/models/gguf/behemoth/q_4/TheDrummer_Behemoth-R1-123B-v2-Q4_K_M-00001-of-00002.gguf"
                - "-ngl"
                - "99"
                - -fa
                - -t
                - "-1"
                - --prio
                - "3"
                - --numa
                - distribute
                - --alias
                - "behemoth"
            - name: qwen3-235b
              cooldownPeriod: 3600
              resources:
                requests:
                  nvidia.com/gpu: 6
                limits:
                  nvidia.com/gpu: 6
              args:
                - -ctv
                - q8_0
                - -ctk
                - q8_0
                - --presence-penalty 
                - "1.0"
                - --ctx-size
                - "262144"
                - --temp
                - "0.6"
                - --min-p
                - "0.0"
                - --top-p
                - "0.95"
                - --top-k
                - "20"
                - --no-mmap
                - --jinja
                - "-m"
                - "/models/gguf/Qwen3-235B-A22B-2507/Qwen3-235B-A22B-Thinking-2507-UD-Q2_K_XL-00001-of-00002.gguf"
                - "-ngl"
                - "99"
                - -fa
                - -t
                - "-1"
                - --jinja
                - --prio
                - "3"
                - --numa
                - distribute
                - --alias
                - "qwen3-235b"
            - name: qwen3-235b-q8
              cooldownPeriod: 3600
              device: cpu
              args:
                - -t
                - "-1"
                - --jinja
                - -c
                - "131072"
                - -ngl
                - "0"
                - --no-mmap
                - --numa
                - distribute
                - --rope-scaling 
                - yarn 
                - --rope-scale 
                - "4" 
                - --yarn-orig-ctx
                - "32768"
                - -m
                - /models/gguf/Qwen-235B/Qwen3-235B-A22B-128K-UD-Q8_K_XL-00001-of-00006.gguf
              selector: { }
              cpuResources:
                requests:
                  memory: "300Gi"
                limits:
                  memory: "300Gi"
            - name: glm-4-5-air
              cooldownPeriod: 7200
              resources:
                requests:
                  nvidia.com/gpu: 6
                limits:
                  nvidia.com/gpu: 6
              args:
                - --jinja
                - --temp
                - "0.6"
                - --top-p
                - "1.0"
                - -c
                - "131072"
                - --model
                - /models/gguf/glm-air/GLM-4.5-Air-UD-Q6_K_XL-00001-of-00003.gguf
                - -fa
                - -t
                - "-1"
                - --no-mmap
                - --alias
                - glm-4-5-air
            - name: qwen3-coder
              engine: vllm
              cooldownPeriod: 7200
              resources:
                requests:
                  nvidia.com/gpu: 3
                limits:
                  nvidia.com/gpu: 3
              args:
                - --max-num-seqs=2
                - --pipeline-parallel-size=3
                - --port
                - "8080"
                - --model
                - /models/fp8/Qwen3-Coder-30B-A3B-Instruct-W8A8
                - --served-model-name
                - qwen3-coder-plus
                - --enable-auto-tool-choice
                - --tool-call-parser
                - qwen3_coder
                - --enable-expert-parallel
  destination:
    server: https://kubernetes.default.svc
    namespace: inference
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
