name: Renovate

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  renovate:
    runs-on: dind
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Renovate
        uses: renovatebot/github-action@v43.0.17
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
